/* File: coremodule.c
 * This file is auto-generated with f2py (version:1.24.3).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Mon Nov 17 19:07:41 2025
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

#ifndef PY_SSIZE_T_CLEAN
#define PY_SSIZE_T_CLEAN
#endif /* PY_SSIZE_T_CLEAN */

/* Unconditionally included */
#include <Python.h>
#include <numpy/npy_os.h>

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "fortranobject.h"
/*need_includes0*/

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *core_error;
static PyObject *core_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

/* See fortranobject.h for definitions. The macros here are provided for BC. */
#define rank f2py_rank
#define shape f2py_shape
#define fshape f2py_shape
#define len f2py_len
#define flen f2py_flen
#define slen f2py_slen
#define size f2py_size

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int
double_from_pyobj(double* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
        *v = PyFloat_AsDouble(obj);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    tmp = PyNumber_Float(obj);
    if (tmp) {
        *v = PyFloat_AsDouble(tmp);
        Py_DECREF(tmp);
        return !(*v == -1.0 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = core_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int
int_from_pyobj(int* v, PyObject *obj, const char *errmess)
{
    PyObject* tmp = NULL;

    if (PyLong_Check(obj)) {
        *v = Npy__PyLong_AsInt(obj);
        return !(*v == -1 && PyErr_Occurred());
    }

    tmp = PyNumber_Long(obj);
    if (tmp) {
        *v = Npy__PyLong_AsInt(tmp);
        Py_DECREF(tmp);
        return !(*v == -1 && PyErr_Occurred());
    }

    if (PyComplex_Check(obj)) {
        PyErr_Clear();
        tmp = PyObject_GetAttrString(obj,"real");
    }
    else if (PyBytes_Check(obj) || PyUnicode_Check(obj)) {
        /*pass*/;
    }
    else if (PySequence_Check(obj)) {
        PyErr_Clear();
        tmp = PySequence_GetItem(obj, 0);
    }

    if (tmp) {
        if (int_from_pyobj(v, tmp, errmess)) {
            Py_DECREF(tmp);
            return 1;
        }
        Py_DECREF(tmp);
    }

    {
        PyObject* err = PyErr_Occurred();
        if (err == NULL) {
            err = core_error;
        }
        PyErr_SetString(err, errmess);
    }
    return 0;
}

static int
float_from_pyobj(float* v, PyObject *obj, const char *errmess)
{
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(subgreen,SUBGREEN)(int*,int*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,float*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*);
extern void F_FUNC(subgreen2,SUBGREEN2)(int*,int*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,float*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** subgreen **********************************/
static char doc_f2py_rout_core_subgreen[] = "\
tdata,zz,ee,nn,t0 = subgreen(mb,src,rcv,stype,updn,d,a,b,rho,qa,qb,dt,nfft,tb,nx,sigma,smth,wc1,wc2,pmin,pmax,dk,kc,taper,x,pf,df,lf,sx,sy,rx,ry)\n\nWrapper for ``subgreen``.\
\n\nParameters\n----------\n"
"mb : input int\n"
"src : input int\n"
"rcv : input int\n"
"stype : input int\n"
"updn : input int\n"
"d : input rank-1 array('f') with bounds (mb)\n"
"a : input rank-1 array('f') with bounds (mb)\n"
"b : input rank-1 array('f') with bounds (mb)\n"
"rho : input rank-1 array('f') with bounds (mb)\n"
"qa : input rank-1 array('f') with bounds (mb)\n"
"qb : input rank-1 array('f') with bounds (mb)\n"
"dt : input float\n"
"nfft : input int\n"
"tb : input int\n"
"nx : input int\n"
"sigma : input float\n"
"smth : input int\n"
"wc1 : input int\n"
"wc2 : input int\n"
"pmin : input float\n"
"pmax : input float\n"
"dk : input float\n"
"kc : input float\n"
"taper : input float\n"
"x : input rank-1 array('f') with bounds (nx)\n"
"pf : input float\n"
"df : input float\n"
"lf : input float\n"
"sx : input float\n"
"sy : input float\n"
"rx : input float\n"
"ry : input float\n"
"\nReturns\n-------\n"
"tdata : rank-3 array('f') with bounds (nx,9,2 * nfft)\n"
"zz : rank-1 array('f') with bounds (2 * nfft)\n"
"ee : rank-1 array('f') with bounds (2 * nfft)\n"
"nn : rank-1 array('f') with bounds (2 * nfft)\n"
"t0 : rank-1 array('f') with bounds (nx)";
/* extern void F_FUNC(subgreen,SUBGREEN)(int*,int*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,float*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_core_subgreen(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,float*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int mb = 0;
    PyObject *mb_capi = Py_None;
    int src = 0;
    PyObject *src_capi = Py_None;
    int rcv = 0;
    PyObject *rcv_capi = Py_None;
    int stype = 0;
    PyObject *stype_capi = Py_None;
    int updn = 0;
    PyObject *updn_capi = Py_None;
    float *d = NULL;
    npy_intp d_Dims[1] = {-1};
    const int d_Rank = 1;
    PyArrayObject *capi_d_as_array = NULL;
    int capi_d_intent = 0;
    PyObject *d_capi = Py_None;
    float *a = NULL;
    npy_intp a_Dims[1] = {-1};
    const int a_Rank = 1;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    float *b = NULL;
    npy_intp b_Dims[1] = {-1};
    const int b_Rank = 1;
    PyArrayObject *capi_b_as_array = NULL;
    int capi_b_intent = 0;
    PyObject *b_capi = Py_None;
    float *rho = NULL;
    npy_intp rho_Dims[1] = {-1};
    const int rho_Rank = 1;
    PyArrayObject *capi_rho_as_array = NULL;
    int capi_rho_intent = 0;
    PyObject *rho_capi = Py_None;
    float *qa = NULL;
    npy_intp qa_Dims[1] = {-1};
    const int qa_Rank = 1;
    PyArrayObject *capi_qa_as_array = NULL;
    int capi_qa_intent = 0;
    PyObject *qa_capi = Py_None;
    float *qb = NULL;
    npy_intp qb_Dims[1] = {-1};
    const int qb_Rank = 1;
    PyArrayObject *capi_qb_as_array = NULL;
    int capi_qb_intent = 0;
    PyObject *qb_capi = Py_None;
    float dt = 0;
    PyObject *dt_capi = Py_None;
    int nfft = 0;
    PyObject *nfft_capi = Py_None;
    int tb = 0;
    PyObject *tb_capi = Py_None;
    int nx = 0;
    PyObject *nx_capi = Py_None;
    float sigma = 0;
    PyObject *sigma_capi = Py_None;
    int smth = 0;
    PyObject *smth_capi = Py_None;
    int wc1 = 0;
    PyObject *wc1_capi = Py_None;
    int wc2 = 0;
    PyObject *wc2_capi = Py_None;
    float pmin = 0;
    PyObject *pmin_capi = Py_None;
    float pmax = 0;
    PyObject *pmax_capi = Py_None;
    float dk = 0;
    PyObject *dk_capi = Py_None;
    float kc = 0;
    PyObject *kc_capi = Py_None;
    float taper = 0;
    PyObject *taper_capi = Py_None;
    float *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    float pf = 0;
    PyObject *pf_capi = Py_None;
    float df = 0;
    PyObject *df_capi = Py_None;
    float lf = 0;
    PyObject *lf_capi = Py_None;
    float *tdata = NULL;
    npy_intp tdata_Dims[3] = {-1, -1, -1};
    const int tdata_Rank = 3;
    PyArrayObject *capi_tdata_as_array = NULL;
    int capi_tdata_intent = 0;
    float sx = 0;
    PyObject *sx_capi = Py_None;
    float sy = 0;
    PyObject *sy_capi = Py_None;
    float rx = 0;
    PyObject *rx_capi = Py_None;
    float ry = 0;
    PyObject *ry_capi = Py_None;
    float *zz = NULL;
    npy_intp zz_Dims[1] = {-1};
    const int zz_Rank = 1;
    PyArrayObject *capi_zz_as_array = NULL;
    int capi_zz_intent = 0;
    float *ee = NULL;
    npy_intp ee_Dims[1] = {-1};
    const int ee_Rank = 1;
    PyArrayObject *capi_ee_as_array = NULL;
    int capi_ee_intent = 0;
    float *nn = NULL;
    npy_intp nn_Dims[1] = {-1};
    const int nn_Rank = 1;
    PyArrayObject *capi_nn_as_array = NULL;
    int capi_nn_intent = 0;
    float *t0 = NULL;
    npy_intp t0_Dims[1] = {-1};
    const int t0_Rank = 1;
    PyArrayObject *capi_t0_as_array = NULL;
    int capi_t0_intent = 0;
    static char *capi_kwlist[] = {"mb","src","rcv","stype","updn","d","a","b","rho","qa","qb","dt","nfft","tb","nx","sigma","smth","wc1","wc2","pmin","pmax","dk","kc","taper","x","pf","df","lf","sx","sy","rx","ry",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|:core.subgreen",\
        capi_kwlist,&mb_capi,&src_capi,&rcv_capi,&stype_capi,&updn_capi,&d_capi,&a_capi,&b_capi,&rho_capi,&qa_capi,&qb_capi,&dt_capi,&nfft_capi,&tb_capi,&nx_capi,&sigma_capi,&smth_capi,&wc1_capi,&wc2_capi,&pmin_capi,&pmax_capi,&dk_capi,&kc_capi,&taper_capi,&x_capi,&pf_capi,&df_capi,&lf_capi,&sx_capi,&sy_capi,&rx_capi,&ry_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable mb */
        f2py_success = int_from_pyobj(&mb,mb_capi,"core.subgreen() 1st argument (mb) can't be converted to int");
    if (f2py_success) {
    /* Processing variable src */
        f2py_success = int_from_pyobj(&src,src_capi,"core.subgreen() 2nd argument (src) can't be converted to int");
    if (f2py_success) {
    /* Processing variable rcv */
        f2py_success = int_from_pyobj(&rcv,rcv_capi,"core.subgreen() 3rd argument (rcv) can't be converted to int");
    if (f2py_success) {
    /* Processing variable stype */
        f2py_success = int_from_pyobj(&stype,stype_capi,"core.subgreen() 4th argument (stype) can't be converted to int");
    if (f2py_success) {
    /* Processing variable updn */
        f2py_success = int_from_pyobj(&updn,updn_capi,"core.subgreen() 5th argument (updn) can't be converted to int");
    if (f2py_success) {
    /* Processing variable dt */
        f2py_success = float_from_pyobj(&dt,dt_capi,"core.subgreen() 12nd argument (dt) can't be converted to float");
    if (f2py_success) {
    /* Processing variable nfft */
        f2py_success = int_from_pyobj(&nfft,nfft_capi,"core.subgreen() 13rd argument (nfft) can't be converted to int");
    if (f2py_success) {
    /* Processing variable tb */
        f2py_success = int_from_pyobj(&tb,tb_capi,"core.subgreen() 14th argument (tb) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nx */
        f2py_success = int_from_pyobj(&nx,nx_capi,"core.subgreen() 15th argument (nx) can't be converted to int");
    if (f2py_success) {
    /* Processing variable sigma */
        f2py_success = float_from_pyobj(&sigma,sigma_capi,"core.subgreen() 16th argument (sigma) can't be converted to float");
    if (f2py_success) {
    /* Processing variable smth */
        f2py_success = int_from_pyobj(&smth,smth_capi,"core.subgreen() 17th argument (smth) can't be converted to int");
    if (f2py_success) {
    /* Processing variable wc1 */
        f2py_success = int_from_pyobj(&wc1,wc1_capi,"core.subgreen() 18th argument (wc1) can't be converted to int");
    if (f2py_success) {
    /* Processing variable wc2 */
        f2py_success = int_from_pyobj(&wc2,wc2_capi,"core.subgreen() 19th argument (wc2) can't be converted to int");
    if (f2py_success) {
    /* Processing variable pmin */
        f2py_success = float_from_pyobj(&pmin,pmin_capi,"core.subgreen() 20th argument (pmin) can't be converted to float");
    if (f2py_success) {
    /* Processing variable pmax */
        f2py_success = float_from_pyobj(&pmax,pmax_capi,"core.subgreen() 21st argument (pmax) can't be converted to float");
    if (f2py_success) {
    /* Processing variable dk */
        f2py_success = float_from_pyobj(&dk,dk_capi,"core.subgreen() 22nd argument (dk) can't be converted to float");
    if (f2py_success) {
    /* Processing variable kc */
        f2py_success = float_from_pyobj(&kc,kc_capi,"core.subgreen() 23rd argument (kc) can't be converted to float");
    if (f2py_success) {
    /* Processing variable taper */
        f2py_success = float_from_pyobj(&taper,taper_capi,"core.subgreen() 24th argument (taper) can't be converted to float");
    if (f2py_success) {
    /* Processing variable pf */
        f2py_success = float_from_pyobj(&pf,pf_capi,"core.subgreen() 26th argument (pf) can't be converted to float");
    if (f2py_success) {
    /* Processing variable df */
        f2py_success = float_from_pyobj(&df,df_capi,"core.subgreen() 27th argument (df) can't be converted to float");
    if (f2py_success) {
    /* Processing variable lf */
        f2py_success = float_from_pyobj(&lf,lf_capi,"core.subgreen() 28th argument (lf) can't be converted to float");
    if (f2py_success) {
    /* Processing variable sx */
        f2py_success = float_from_pyobj(&sx,sx_capi,"core.subgreen() 29th argument (sx) can't be converted to float");
    if (f2py_success) {
    /* Processing variable sy */
        f2py_success = float_from_pyobj(&sy,sy_capi,"core.subgreen() 30th argument (sy) can't be converted to float");
    if (f2py_success) {
    /* Processing variable rx */
        f2py_success = float_from_pyobj(&rx,rx_capi,"core.subgreen() 31st argument (rx) can't be converted to float");
    if (f2py_success) {
    /* Processing variable ry */
        f2py_success = float_from_pyobj(&ry,ry_capi,"core.subgreen() 32nd argument (ry) can't be converted to float");
    if (f2py_success) {
    /* Processing variable d */
    d_Dims[0]=mb;
    capi_d_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the 6th argument `d`";
    capi_d_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,d_Dims,d_Rank,  capi_d_intent,d_capi,capi_errmess);
    if (capi_d_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        d = (float *)(PyArray_DATA(capi_d_as_array));

    /* Processing variable a */
    a_Dims[0]=mb;
    capi_a_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the 7th argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (float *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable b */
    b_Dims[0]=mb;
    capi_b_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the 8th argument `b`";
    capi_b_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,b_Dims,b_Rank,  capi_b_intent,b_capi,capi_errmess);
    if (capi_b_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        b = (float *)(PyArray_DATA(capi_b_as_array));

    /* Processing variable rho */
    rho_Dims[0]=mb;
    capi_rho_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the 9th argument `rho`";
    capi_rho_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,rho_Dims,rho_Rank,  capi_rho_intent,rho_capi,capi_errmess);
    if (capi_rho_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rho = (float *)(PyArray_DATA(capi_rho_as_array));

    /* Processing variable qa */
    qa_Dims[0]=mb;
    capi_qa_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the 10th argument `qa`";
    capi_qa_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,qa_Dims,qa_Rank,  capi_qa_intent,qa_capi,capi_errmess);
    if (capi_qa_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        qa = (float *)(PyArray_DATA(capi_qa_as_array));

    /* Processing variable qb */
    qb_Dims[0]=mb;
    capi_qb_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the 11st argument `qb`";
    capi_qb_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,qb_Dims,qb_Rank,  capi_qb_intent,qb_capi,capi_errmess);
    if (capi_qb_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        qb = (float *)(PyArray_DATA(capi_qb_as_array));

    /* Processing variable x */
    x_Dims[0]=nx;
    capi_x_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the 25th argument `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,x_Dims,x_Rank,  capi_x_intent,x_capi,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (float *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable tdata */
    tdata_Dims[0]=nx,tdata_Dims[1]=9,tdata_Dims[2]=2 * nfft;
    capi_tdata_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the hidden `tdata`";
    capi_tdata_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,tdata_Dims,tdata_Rank,  capi_tdata_intent,Py_None,capi_errmess);
    if (capi_tdata_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        tdata = (float *)(PyArray_DATA(capi_tdata_as_array));

    /* Processing variable zz */
    zz_Dims[0]=2 * nfft;
    capi_zz_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the hidden `zz`";
    capi_zz_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,zz_Dims,zz_Rank,  capi_zz_intent,Py_None,capi_errmess);
    if (capi_zz_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        zz = (float *)(PyArray_DATA(capi_zz_as_array));

    /* Processing variable ee */
    ee_Dims[0]=2 * nfft;
    capi_ee_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the hidden `ee`";
    capi_ee_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,ee_Dims,ee_Rank,  capi_ee_intent,Py_None,capi_errmess);
    if (capi_ee_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ee = (float *)(PyArray_DATA(capi_ee_as_array));

    /* Processing variable nn */
    nn_Dims[0]=2 * nfft;
    capi_nn_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the hidden `nn`";
    capi_nn_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,nn_Dims,nn_Rank,  capi_nn_intent,Py_None,capi_errmess);
    if (capi_nn_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nn = (float *)(PyArray_DATA(capi_nn_as_array));

    /* Processing variable t0 */
    t0_Dims[0]=nx;
    capi_t0_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "core.core.subgreen: failed to create array from the hidden `t0`";
    capi_t0_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,t0_Dims,t0_Rank,  capi_t0_intent,Py_None,capi_errmess);
    if (capi_t0_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        t0 = (float *)(PyArray_DATA(capi_t0_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&mb,&src,&rcv,&stype,&updn,d,a,b,rho,qa,qb,&dt,&nfft,&tb,&nx,&sigma,&smth,&wc1,&wc2,&pmin,&pmax,&dk,&kc,&taper,x,&pf,&df,&lf,tdata,&sx,&sy,&rx,&ry,zz,ee,nn,t0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNNNN",capi_tdata_as_array,capi_zz_as_array,capi_ee_as_array,capi_nn_as_array,capi_t0_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_t0_as_array == NULL) ... else of t0 */
    /* End of cleaning variable t0 */
    }  /* if (capi_nn_as_array == NULL) ... else of nn */
    /* End of cleaning variable nn */
    }  /* if (capi_ee_as_array == NULL) ... else of ee */
    /* End of cleaning variable ee */
    }  /* if (capi_zz_as_array == NULL) ... else of zz */
    /* End of cleaning variable zz */
    }  /* if (capi_tdata_as_array == NULL) ... else of tdata */
    /* End of cleaning variable tdata */
    if((PyObject *)capi_x_as_array!=x_capi) {
        Py_XDECREF(capi_x_as_array); }
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
    if((PyObject *)capi_qb_as_array!=qb_capi) {
        Py_XDECREF(capi_qb_as_array); }
    }  /* if (capi_qb_as_array == NULL) ... else of qb */
    /* End of cleaning variable qb */
    if((PyObject *)capi_qa_as_array!=qa_capi) {
        Py_XDECREF(capi_qa_as_array); }
    }  /* if (capi_qa_as_array == NULL) ... else of qa */
    /* End of cleaning variable qa */
    if((PyObject *)capi_rho_as_array!=rho_capi) {
        Py_XDECREF(capi_rho_as_array); }
    }  /* if (capi_rho_as_array == NULL) ... else of rho */
    /* End of cleaning variable rho */
    if((PyObject *)capi_b_as_array!=b_capi) {
        Py_XDECREF(capi_b_as_array); }
    }  /* if (capi_b_as_array == NULL) ... else of b */
    /* End of cleaning variable b */
    if((PyObject *)capi_a_as_array!=a_capi) {
        Py_XDECREF(capi_a_as_array); }
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
    if((PyObject *)capi_d_as_array!=d_capi) {
        Py_XDECREF(capi_d_as_array); }
    }  /* if (capi_d_as_array == NULL) ... else of d */
    /* End of cleaning variable d */
    } /*if (f2py_success) of ry*/
    /* End of cleaning variable ry */
    } /*if (f2py_success) of rx*/
    /* End of cleaning variable rx */
    } /*if (f2py_success) of sy*/
    /* End of cleaning variable sy */
    } /*if (f2py_success) of sx*/
    /* End of cleaning variable sx */
    } /*if (f2py_success) of lf*/
    /* End of cleaning variable lf */
    } /*if (f2py_success) of df*/
    /* End of cleaning variable df */
    } /*if (f2py_success) of pf*/
    /* End of cleaning variable pf */
    } /*if (f2py_success) of taper*/
    /* End of cleaning variable taper */
    } /*if (f2py_success) of kc*/
    /* End of cleaning variable kc */
    } /*if (f2py_success) of dk*/
    /* End of cleaning variable dk */
    } /*if (f2py_success) of pmax*/
    /* End of cleaning variable pmax */
    } /*if (f2py_success) of pmin*/
    /* End of cleaning variable pmin */
    } /*if (f2py_success) of wc2*/
    /* End of cleaning variable wc2 */
    } /*if (f2py_success) of wc1*/
    /* End of cleaning variable wc1 */
    } /*if (f2py_success) of smth*/
    /* End of cleaning variable smth */
    } /*if (f2py_success) of sigma*/
    /* End of cleaning variable sigma */
    } /*if (f2py_success) of nx*/
    /* End of cleaning variable nx */
    } /*if (f2py_success) of tb*/
    /* End of cleaning variable tb */
    } /*if (f2py_success) of nfft*/
    /* End of cleaning variable nfft */
    } /*if (f2py_success) of dt*/
    /* End of cleaning variable dt */
    } /*if (f2py_success) of updn*/
    /* End of cleaning variable updn */
    } /*if (f2py_success) of stype*/
    /* End of cleaning variable stype */
    } /*if (f2py_success) of rcv*/
    /* End of cleaning variable rcv */
    } /*if (f2py_success) of src*/
    /* End of cleaning variable src */
    } /*if (f2py_success) of mb*/
    /* End of cleaning variable mb */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of subgreen ******************************/

/********************************* subgreen2 *********************************/
static char doc_f2py_rout_core_subgreen2[] = "\
zz,ee,nn,t0 = subgreen2(mb,src,rcv,stype,updn,d,a,b,rho,qa,qb,dt,nfft,tb,nx,sigma,smth,wc1,wc2,pmin,pmax,dk,kc,taper,x,pf,df,lf,tdata,sx,sy,rx,ry)\n\nWrapper for ``subgreen2``.\
\n\nParameters\n----------\n"
"mb : input int\n"
"src : input int\n"
"rcv : input int\n"
"stype : input int\n"
"updn : input int\n"
"d : input rank-1 array('f') with bounds (mb)\n"
"a : input rank-1 array('f') with bounds (mb)\n"
"b : input rank-1 array('f') with bounds (mb)\n"
"rho : input rank-1 array('f') with bounds (mb)\n"
"qa : input rank-1 array('f') with bounds (mb)\n"
"qb : input rank-1 array('f') with bounds (mb)\n"
"dt : input float\n"
"nfft : input int\n"
"tb : input int\n"
"nx : input int\n"
"sigma : input float\n"
"smth : input int\n"
"wc1 : input int\n"
"wc2 : input int\n"
"pmin : input float\n"
"pmax : input float\n"
"dk : input float\n"
"kc : input float\n"
"taper : input float\n"
"x : input rank-1 array('f') with bounds (nx)\n"
"pf : input float\n"
"df : input float\n"
"lf : input float\n"
"tdata : input rank-3 array('f') with bounds (nx,9,2 * nfft)\n"
"sx : input float\n"
"sy : input float\n"
"rx : input float\n"
"ry : input float\n"
"\nReturns\n-------\n"
"zz : rank-1 array('f') with bounds (2 * nfft)\n"
"ee : rank-1 array('f') with bounds (2 * nfft)\n"
"nn : rank-1 array('f') with bounds (2 * nfft)\n"
"t0 : rank-1 array('f') with bounds (nx)";
/* extern void F_FUNC(subgreen2,SUBGREEN2)(int*,int*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,float*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*); */
static PyObject *f2py_rout_core_subgreen2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,int*,int*,int*,float*,int*,int*,int*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*,float*)) {
    PyObject * volatile capi_buildvalue = NULL;
    volatile int f2py_success = 1;
/*decl*/

    int mb = 0;
    PyObject *mb_capi = Py_None;
    int src = 0;
    PyObject *src_capi = Py_None;
    int rcv = 0;
    PyObject *rcv_capi = Py_None;
    int stype = 0;
    PyObject *stype_capi = Py_None;
    int updn = 0;
    PyObject *updn_capi = Py_None;
    float *d = NULL;
    npy_intp d_Dims[1] = {-1};
    const int d_Rank = 1;
    PyArrayObject *capi_d_as_array = NULL;
    int capi_d_intent = 0;
    PyObject *d_capi = Py_None;
    float *a = NULL;
    npy_intp a_Dims[1] = {-1};
    const int a_Rank = 1;
    PyArrayObject *capi_a_as_array = NULL;
    int capi_a_intent = 0;
    PyObject *a_capi = Py_None;
    float *b = NULL;
    npy_intp b_Dims[1] = {-1};
    const int b_Rank = 1;
    PyArrayObject *capi_b_as_array = NULL;
    int capi_b_intent = 0;
    PyObject *b_capi = Py_None;
    float *rho = NULL;
    npy_intp rho_Dims[1] = {-1};
    const int rho_Rank = 1;
    PyArrayObject *capi_rho_as_array = NULL;
    int capi_rho_intent = 0;
    PyObject *rho_capi = Py_None;
    float *qa = NULL;
    npy_intp qa_Dims[1] = {-1};
    const int qa_Rank = 1;
    PyArrayObject *capi_qa_as_array = NULL;
    int capi_qa_intent = 0;
    PyObject *qa_capi = Py_None;
    float *qb = NULL;
    npy_intp qb_Dims[1] = {-1};
    const int qb_Rank = 1;
    PyArrayObject *capi_qb_as_array = NULL;
    int capi_qb_intent = 0;
    PyObject *qb_capi = Py_None;
    float dt = 0;
    PyObject *dt_capi = Py_None;
    int nfft = 0;
    PyObject *nfft_capi = Py_None;
    int tb = 0;
    PyObject *tb_capi = Py_None;
    int nx = 0;
    PyObject *nx_capi = Py_None;
    float sigma = 0;
    PyObject *sigma_capi = Py_None;
    int smth = 0;
    PyObject *smth_capi = Py_None;
    int wc1 = 0;
    PyObject *wc1_capi = Py_None;
    int wc2 = 0;
    PyObject *wc2_capi = Py_None;
    float pmin = 0;
    PyObject *pmin_capi = Py_None;
    float pmax = 0;
    PyObject *pmax_capi = Py_None;
    float dk = 0;
    PyObject *dk_capi = Py_None;
    float kc = 0;
    PyObject *kc_capi = Py_None;
    float taper = 0;
    PyObject *taper_capi = Py_None;
    float *x = NULL;
    npy_intp x_Dims[1] = {-1};
    const int x_Rank = 1;
    PyArrayObject *capi_x_as_array = NULL;
    int capi_x_intent = 0;
    PyObject *x_capi = Py_None;
    float pf = 0;
    PyObject *pf_capi = Py_None;
    float df = 0;
    PyObject *df_capi = Py_None;
    float lf = 0;
    PyObject *lf_capi = Py_None;
    float *tdata = NULL;
    npy_intp tdata_Dims[3] = {-1, -1, -1};
    const int tdata_Rank = 3;
    PyArrayObject *capi_tdata_as_array = NULL;
    int capi_tdata_intent = 0;
    PyObject *tdata_capi = Py_None;
    float sx = 0;
    PyObject *sx_capi = Py_None;
    float sy = 0;
    PyObject *sy_capi = Py_None;
    float rx = 0;
    PyObject *rx_capi = Py_None;
    float ry = 0;
    PyObject *ry_capi = Py_None;
    float *zz = NULL;
    npy_intp zz_Dims[1] = {-1};
    const int zz_Rank = 1;
    PyArrayObject *capi_zz_as_array = NULL;
    int capi_zz_intent = 0;
    float *ee = NULL;
    npy_intp ee_Dims[1] = {-1};
    const int ee_Rank = 1;
    PyArrayObject *capi_ee_as_array = NULL;
    int capi_ee_intent = 0;
    float *nn = NULL;
    npy_intp nn_Dims[1] = {-1};
    const int nn_Rank = 1;
    PyArrayObject *capi_nn_as_array = NULL;
    int capi_nn_intent = 0;
    float *t0 = NULL;
    npy_intp t0_Dims[1] = {-1};
    const int t0_Rank = 1;
    PyArrayObject *capi_t0_as_array = NULL;
    int capi_t0_intent = 0;
    static char *capi_kwlist[] = {"mb","src","rcv","stype","updn","d","a","b","rho","qa","qb","dt","nfft","tb","nx","sigma","smth","wc1","wc2","pmin","pmax","dk","kc","taper","x","pf","df","lf","tdata","sx","sy","rx","ry",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
    if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
        "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|:core.subgreen2",\
        capi_kwlist,&mb_capi,&src_capi,&rcv_capi,&stype_capi,&updn_capi,&d_capi,&a_capi,&b_capi,&rho_capi,&qa_capi,&qb_capi,&dt_capi,&nfft_capi,&tb_capi,&nx_capi,&sigma_capi,&smth_capi,&wc1_capi,&wc2_capi,&pmin_capi,&pmax_capi,&dk_capi,&kc_capi,&taper_capi,&x_capi,&pf_capi,&df_capi,&lf_capi,&tdata_capi,&sx_capi,&sy_capi,&rx_capi,&ry_capi))
        return NULL;
/*frompyobj*/
    /* Processing variable mb */
        f2py_success = int_from_pyobj(&mb,mb_capi,"core.subgreen2() 1st argument (mb) can't be converted to int");
    if (f2py_success) {
    /* Processing variable src */
        f2py_success = int_from_pyobj(&src,src_capi,"core.subgreen2() 2nd argument (src) can't be converted to int");
    if (f2py_success) {
    /* Processing variable rcv */
        f2py_success = int_from_pyobj(&rcv,rcv_capi,"core.subgreen2() 3rd argument (rcv) can't be converted to int");
    if (f2py_success) {
    /* Processing variable stype */
        f2py_success = int_from_pyobj(&stype,stype_capi,"core.subgreen2() 4th argument (stype) can't be converted to int");
    if (f2py_success) {
    /* Processing variable updn */
        f2py_success = int_from_pyobj(&updn,updn_capi,"core.subgreen2() 5th argument (updn) can't be converted to int");
    if (f2py_success) {
    /* Processing variable dt */
        f2py_success = float_from_pyobj(&dt,dt_capi,"core.subgreen2() 12nd argument (dt) can't be converted to float");
    if (f2py_success) {
    /* Processing variable nfft */
        f2py_success = int_from_pyobj(&nfft,nfft_capi,"core.subgreen2() 13rd argument (nfft) can't be converted to int");
    if (f2py_success) {
    /* Processing variable tb */
        f2py_success = int_from_pyobj(&tb,tb_capi,"core.subgreen2() 14th argument (tb) can't be converted to int");
    if (f2py_success) {
    /* Processing variable nx */
        f2py_success = int_from_pyobj(&nx,nx_capi,"core.subgreen2() 15th argument (nx) can't be converted to int");
    if (f2py_success) {
    /* Processing variable sigma */
        f2py_success = float_from_pyobj(&sigma,sigma_capi,"core.subgreen2() 16th argument (sigma) can't be converted to float");
    if (f2py_success) {
    /* Processing variable smth */
        f2py_success = int_from_pyobj(&smth,smth_capi,"core.subgreen2() 17th argument (smth) can't be converted to int");
    if (f2py_success) {
    /* Processing variable wc1 */
        f2py_success = int_from_pyobj(&wc1,wc1_capi,"core.subgreen2() 18th argument (wc1) can't be converted to int");
    if (f2py_success) {
    /* Processing variable wc2 */
        f2py_success = int_from_pyobj(&wc2,wc2_capi,"core.subgreen2() 19th argument (wc2) can't be converted to int");
    if (f2py_success) {
    /* Processing variable pmin */
        f2py_success = float_from_pyobj(&pmin,pmin_capi,"core.subgreen2() 20th argument (pmin) can't be converted to float");
    if (f2py_success) {
    /* Processing variable pmax */
        f2py_success = float_from_pyobj(&pmax,pmax_capi,"core.subgreen2() 21st argument (pmax) can't be converted to float");
    if (f2py_success) {
    /* Processing variable dk */
        f2py_success = float_from_pyobj(&dk,dk_capi,"core.subgreen2() 22nd argument (dk) can't be converted to float");
    if (f2py_success) {
    /* Processing variable kc */
        f2py_success = float_from_pyobj(&kc,kc_capi,"core.subgreen2() 23rd argument (kc) can't be converted to float");
    if (f2py_success) {
    /* Processing variable taper */
        f2py_success = float_from_pyobj(&taper,taper_capi,"core.subgreen2() 24th argument (taper) can't be converted to float");
    if (f2py_success) {
    /* Processing variable pf */
        f2py_success = float_from_pyobj(&pf,pf_capi,"core.subgreen2() 26th argument (pf) can't be converted to float");
    if (f2py_success) {
    /* Processing variable df */
        f2py_success = float_from_pyobj(&df,df_capi,"core.subgreen2() 27th argument (df) can't be converted to float");
    if (f2py_success) {
    /* Processing variable lf */
        f2py_success = float_from_pyobj(&lf,lf_capi,"core.subgreen2() 28th argument (lf) can't be converted to float");
    if (f2py_success) {
    /* Processing variable sx */
        f2py_success = float_from_pyobj(&sx,sx_capi,"core.subgreen2() 30th argument (sx) can't be converted to float");
    if (f2py_success) {
    /* Processing variable sy */
        f2py_success = float_from_pyobj(&sy,sy_capi,"core.subgreen2() 31st argument (sy) can't be converted to float");
    if (f2py_success) {
    /* Processing variable rx */
        f2py_success = float_from_pyobj(&rx,rx_capi,"core.subgreen2() 32nd argument (rx) can't be converted to float");
    if (f2py_success) {
    /* Processing variable ry */
        f2py_success = float_from_pyobj(&ry,ry_capi,"core.subgreen2() 33rd argument (ry) can't be converted to float");
    if (f2py_success) {
    /* Processing variable d */
    d_Dims[0]=mb;
    capi_d_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the 6th argument `d`";
    capi_d_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,d_Dims,d_Rank,  capi_d_intent,d_capi,capi_errmess);
    if (capi_d_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        d = (float *)(PyArray_DATA(capi_d_as_array));

    /* Processing variable a */
    a_Dims[0]=mb;
    capi_a_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the 7th argument `a`";
    capi_a_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,a_Dims,a_Rank,  capi_a_intent,a_capi,capi_errmess);
    if (capi_a_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        a = (float *)(PyArray_DATA(capi_a_as_array));

    /* Processing variable b */
    b_Dims[0]=mb;
    capi_b_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the 8th argument `b`";
    capi_b_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,b_Dims,b_Rank,  capi_b_intent,b_capi,capi_errmess);
    if (capi_b_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        b = (float *)(PyArray_DATA(capi_b_as_array));

    /* Processing variable rho */
    rho_Dims[0]=mb;
    capi_rho_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the 9th argument `rho`";
    capi_rho_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,rho_Dims,rho_Rank,  capi_rho_intent,rho_capi,capi_errmess);
    if (capi_rho_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        rho = (float *)(PyArray_DATA(capi_rho_as_array));

    /* Processing variable qa */
    qa_Dims[0]=mb;
    capi_qa_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the 10th argument `qa`";
    capi_qa_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,qa_Dims,qa_Rank,  capi_qa_intent,qa_capi,capi_errmess);
    if (capi_qa_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        qa = (float *)(PyArray_DATA(capi_qa_as_array));

    /* Processing variable qb */
    qb_Dims[0]=mb;
    capi_qb_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the 11st argument `qb`";
    capi_qb_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,qb_Dims,qb_Rank,  capi_qb_intent,qb_capi,capi_errmess);
    if (capi_qb_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        qb = (float *)(PyArray_DATA(capi_qb_as_array));

    /* Processing variable x */
    x_Dims[0]=nx;
    capi_x_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the 25th argument `x`";
    capi_x_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,x_Dims,x_Rank,  capi_x_intent,x_capi,capi_errmess);
    if (capi_x_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        x = (float *)(PyArray_DATA(capi_x_as_array));

    /* Processing variable tdata */
    tdata_Dims[0]=nx,tdata_Dims[1]=9,tdata_Dims[2]=2 * nfft;
    capi_tdata_intent |= F2PY_INTENT_IN;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the 29th argument `tdata`";
    capi_tdata_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,tdata_Dims,tdata_Rank,  capi_tdata_intent,tdata_capi,capi_errmess);
    if (capi_tdata_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        tdata = (float *)(PyArray_DATA(capi_tdata_as_array));

    /* Processing variable zz */
    zz_Dims[0]=2 * nfft;
    capi_zz_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the hidden `zz`";
    capi_zz_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,zz_Dims,zz_Rank,  capi_zz_intent,Py_None,capi_errmess);
    if (capi_zz_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        zz = (float *)(PyArray_DATA(capi_zz_as_array));

    /* Processing variable ee */
    ee_Dims[0]=2 * nfft;
    capi_ee_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the hidden `ee`";
    capi_ee_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,ee_Dims,ee_Rank,  capi_ee_intent,Py_None,capi_errmess);
    if (capi_ee_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        ee = (float *)(PyArray_DATA(capi_ee_as_array));

    /* Processing variable nn */
    nn_Dims[0]=2 * nfft;
    capi_nn_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the hidden `nn`";
    capi_nn_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,nn_Dims,nn_Rank,  capi_nn_intent,Py_None,capi_errmess);
    if (capi_nn_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        nn = (float *)(PyArray_DATA(capi_nn_as_array));

    /* Processing variable t0 */
    t0_Dims[0]=nx;
    capi_t0_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
    const char * capi_errmess = "core.core.subgreen2: failed to create array from the hidden `t0`";
    capi_t0_as_array = ndarray_from_pyobj(  NPY_FLOAT,1,t0_Dims,t0_Rank,  capi_t0_intent,Py_None,capi_errmess);
    if (capi_t0_as_array == NULL) {
        PyObject* capi_err = PyErr_Occurred();
        if (capi_err == NULL) {
            capi_err = core_error;
            PyErr_SetString(capi_err, capi_errmess);
        }
    } else {
        t0 = (float *)(PyArray_DATA(capi_t0_as_array));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
                (*f2py_func)(&mb,&src,&rcv,&stype,&updn,d,a,b,rho,qa,qb,&dt,&nfft,&tb,&nx,&sigma,&smth,&wc1,&wc2,&pmin,&pmax,&dk,&kc,&taper,x,&pf,&df,&lf,tdata,&sx,&sy,&rx,&ry,zz,ee,nn,t0);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
        if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
        CFUNCSMESS("Building return value.\n");
        capi_buildvalue = Py_BuildValue("NNNN",capi_zz_as_array,capi_ee_as_array,capi_nn_as_array,capi_t0_as_array);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
        } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    }  /* if (capi_t0_as_array == NULL) ... else of t0 */
    /* End of cleaning variable t0 */
    }  /* if (capi_nn_as_array == NULL) ... else of nn */
    /* End of cleaning variable nn */
    }  /* if (capi_ee_as_array == NULL) ... else of ee */
    /* End of cleaning variable ee */
    }  /* if (capi_zz_as_array == NULL) ... else of zz */
    /* End of cleaning variable zz */
    if((PyObject *)capi_tdata_as_array!=tdata_capi) {
        Py_XDECREF(capi_tdata_as_array); }
    }  /* if (capi_tdata_as_array == NULL) ... else of tdata */
    /* End of cleaning variable tdata */
    if((PyObject *)capi_x_as_array!=x_capi) {
        Py_XDECREF(capi_x_as_array); }
    }  /* if (capi_x_as_array == NULL) ... else of x */
    /* End of cleaning variable x */
    if((PyObject *)capi_qb_as_array!=qb_capi) {
        Py_XDECREF(capi_qb_as_array); }
    }  /* if (capi_qb_as_array == NULL) ... else of qb */
    /* End of cleaning variable qb */
    if((PyObject *)capi_qa_as_array!=qa_capi) {
        Py_XDECREF(capi_qa_as_array); }
    }  /* if (capi_qa_as_array == NULL) ... else of qa */
    /* End of cleaning variable qa */
    if((PyObject *)capi_rho_as_array!=rho_capi) {
        Py_XDECREF(capi_rho_as_array); }
    }  /* if (capi_rho_as_array == NULL) ... else of rho */
    /* End of cleaning variable rho */
    if((PyObject *)capi_b_as_array!=b_capi) {
        Py_XDECREF(capi_b_as_array); }
    }  /* if (capi_b_as_array == NULL) ... else of b */
    /* End of cleaning variable b */
    if((PyObject *)capi_a_as_array!=a_capi) {
        Py_XDECREF(capi_a_as_array); }
    }  /* if (capi_a_as_array == NULL) ... else of a */
    /* End of cleaning variable a */
    if((PyObject *)capi_d_as_array!=d_capi) {
        Py_XDECREF(capi_d_as_array); }
    }  /* if (capi_d_as_array == NULL) ... else of d */
    /* End of cleaning variable d */
    } /*if (f2py_success) of ry*/
    /* End of cleaning variable ry */
    } /*if (f2py_success) of rx*/
    /* End of cleaning variable rx */
    } /*if (f2py_success) of sy*/
    /* End of cleaning variable sy */
    } /*if (f2py_success) of sx*/
    /* End of cleaning variable sx */
    } /*if (f2py_success) of lf*/
    /* End of cleaning variable lf */
    } /*if (f2py_success) of df*/
    /* End of cleaning variable df */
    } /*if (f2py_success) of pf*/
    /* End of cleaning variable pf */
    } /*if (f2py_success) of taper*/
    /* End of cleaning variable taper */
    } /*if (f2py_success) of kc*/
    /* End of cleaning variable kc */
    } /*if (f2py_success) of dk*/
    /* End of cleaning variable dk */
    } /*if (f2py_success) of pmax*/
    /* End of cleaning variable pmax */
    } /*if (f2py_success) of pmin*/
    /* End of cleaning variable pmin */
    } /*if (f2py_success) of wc2*/
    /* End of cleaning variable wc2 */
    } /*if (f2py_success) of wc1*/
    /* End of cleaning variable wc1 */
    } /*if (f2py_success) of smth*/
    /* End of cleaning variable smth */
    } /*if (f2py_success) of sigma*/
    /* End of cleaning variable sigma */
    } /*if (f2py_success) of nx*/
    /* End of cleaning variable nx */
    } /*if (f2py_success) of tb*/
    /* End of cleaning variable tb */
    } /*if (f2py_success) of nfft*/
    /* End of cleaning variable nfft */
    } /*if (f2py_success) of dt*/
    /* End of cleaning variable dt */
    } /*if (f2py_success) of updn*/
    /* End of cleaning variable updn */
    } /*if (f2py_success) of stype*/
    /* End of cleaning variable stype */
    } /*if (f2py_success) of rcv*/
    /* End of cleaning variable rcv */
    } /*if (f2py_success) of src*/
    /* End of cleaning variable src */
    } /*if (f2py_success) of mb*/
    /* End of cleaning variable mb */
/*end of cleanupfrompyobj*/
    if (capi_buildvalue == NULL) {
/*routdebugfailure*/
    } else {
/*routdebugleave*/
    }
    CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
    return capi_buildvalue;
}
/****************************** end of subgreen2 ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
    {"subgreen",-1,{{-1}},0,0,(char *)  F_FUNC(subgreen,SUBGREEN),  (f2py_init_func)f2py_rout_core_subgreen,doc_f2py_rout_core_subgreen},
    {"subgreen2",-1,{{-1}},0,0,(char *)  F_FUNC(subgreen2,SUBGREEN2),  (f2py_init_func)f2py_rout_core_subgreen2,doc_f2py_rout_core_subgreen2},

/*eof routine_defs*/
    {NULL}
};

static PyMethodDef f2py_module_methods[] = {

    {NULL,NULL}
};

static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "core",
    NULL,
    -1,
    f2py_module_methods,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC PyInit_core(void) {
    int i;
    PyObject *m,*d, *s, *tmp;
    m = core_module = PyModule_Create(&moduledef);
    Py_SET_TYPE(&PyFortran_Type, &PyType_Type);
    import_array();
    if (PyErr_Occurred())
        {PyErr_SetString(PyExc_ImportError, "can't initialize module core (failed to import numpy)"); return m;}
    d = PyModule_GetDict(m);
    s = PyUnicode_FromString("1.24.3");
    PyDict_SetItemString(d, "__version__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString(
        "This module 'core' is auto-generated with f2py (version:1.24.3).\nFunctions:\n"
"    tdata,zz,ee,nn,t0 = subgreen(mb,src,rcv,stype,updn,d,a,b,rho,qa,qb,dt,nfft,tb,nx,sigma,smth,wc1,wc2,pmin,pmax,dk,kc,taper,x,pf,df,lf,sx,sy,rx,ry)\n"
"    zz,ee,nn,t0 = subgreen2(mb,src,rcv,stype,updn,d,a,b,rho,qa,qb,dt,nfft,tb,nx,sigma,smth,wc1,wc2,pmin,pmax,dk,kc,taper,x,pf,df,lf,tdata,sx,sy,rx,ry)\n"
".");
    PyDict_SetItemString(d, "__doc__", s);
    Py_DECREF(s);
    s = PyUnicode_FromString("1.24.3");
    PyDict_SetItemString(d, "__f2py_numpy_version__", s);
    Py_DECREF(s);
    core_error = PyErr_NewException ("core.error", NULL, NULL);
    /*
     * Store the error object inside the dict, so that it could get deallocated.
     * (in practice, this is a module, so it likely will not and cannot.)
     */
    PyDict_SetItemString(d, "_core_error", core_error);
    Py_DECREF(core_error);
    for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
        tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
        PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
        Py_DECREF(tmp);
    }


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
    if (! PyErr_Occurred())
        on_exit(f2py_report_on_exit,(void*)"core");
#endif
    return m;
}
#ifdef __cplusplus
}
#endif
